ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.3.7'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.1'
gem 'middleman-sprockets', '~> 4.1.0'
gem 'rouge', '~> 2.0.5'
  <<<<<<< dependabot/bundler/src-api/nokogiri-1.11.0
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '~> 1.11.4'
  =======
gem 'redcarpet', '~> 3.5.1'
gem 'nokogiri', '~> 1.11.4'
  >>>>>>> master
gem "therubyracer"
